spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/demo

spring.datasource.username=postgres.kyqxqdimotzkqjhopwpc

spring.datasource.password=43997k7k415nb

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5

spring.datasource.hikari.minimum-idle=1

spring.sql.init.mode=always